// tab users
module.exports = [
  {
    'id': '0',
    'first_name': 'Jean',
    'last_name': 'Robert',
    'age': 19,
    'gender': 'male',
    'height': 1.70,
    'weight': 89,
    'city': 'Paris',
    'street_number': 67,
    'street_name': 'rue du pont',
    'city_code': '12345',
    'phone': '0101010101',
    'image_profil': '',
    'email': 'ghj@gmail.com',
    'password': 'dragon'
  },
  {
    'id': '1',
    'first_name': 'jean-Michel',
    'last_name': 'Fion',
    'age': 34,
    'gender': 'male',
    'height': 1.70,
    'weight': 120,
    'city': 'Paris',
    'street_number': 67,
    'street_name': 'rue du pont',
    'city_code': '12345',
    'phone': '0101010101',
    'image_profil': '',
    'email': 'ghj@gmail.com',
    'password': 'dragon'
  },
  {
    'id': '2',
    'first_name': 'Celine',
    'last_name': 'Guacamole',
    'age': 25,
    'gender': 'female',
    'height': 1.60,
    'weight': 80,
    'city': 'Paris',
    'street_number': 67,
    'street_name': 'rue du pont',
    'city_code': '12345',
    'phone': '0101010101',
    'image_profil': '',
    'email': 'ghj@gmail.com',
    'password': 'dragon'
  },
  {
    'id': '3',
    'first_name': 'Anne-Jean',
    'last_name': 'Pois',
    'age': 16,
    'gender': 'autre',
    'height': 1.50,
    'weight': 50,
    'city': 'Paris',
    'street_number': 67,
    'street_name': 'rue du pont',
    'city_code': '12345',
    'phone': '0101010101',
    'image_profil': '',
    'email': 'ghj@gmail.com',
    'password': 'dragon'
  }
]
